
package br.com.lheme.estoque.cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AutorizacaoFault", targetNamespace = "http://ws.estoque.lheme.com.br/")
public class AutorizacaoException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InfoFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AutorizacaoException(String message, InfoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AutorizacaoException(String message, InfoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.lheme.estoque.cliente.InfoFault
     */
    public InfoFault getFaultInfo() {
        return faultInfo;
    }

}
