
package br.com.lheme.estoque.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.lheme.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @param filtros
     * @return
     *     returns br.com.lheme.estoque.cliente.ListaItens
     */
    @WebMethod(action = "http://ws.estoque.lheme.com.br/EstoqueWS/todosOsItensRequest")
    @WebResult(name = "itens", targetNamespace = "")
    @RequestWrapper(localName = "todosOsItens", targetNamespace = "http://ws.estoque.lheme.com.br/", className = "br.com.lheme.estoque.cliente.TodosOsItens")
    @ResponseWrapper(localName = "todosOsItensResponse", targetNamespace = "http://ws.estoque.lheme.com.br/", className = "br.com.lheme.estoque.cliente.TodosOsItensResponse")
    @Action(input = "http://ws.estoque.lheme.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.lheme.com.br/EstoqueWS/todosOsItensResponse")
    public ListaItens todosOsItens(
        @WebParam(name = "filtros", targetNamespace = "")
        Filtros filtros);

    /**
     * 
     * @param tokenUsuario
     * @param parameters
     * @return
     *     returns br.com.lheme.estoque.cliente.CadastrarItemResponse
     * @throws AutorizacaoException
     */
    @WebMethod(action = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItemRequest")
    @WebResult(name = "cadastrarItemResponse", targetNamespace = "http://ws.estoque.lheme.com.br/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItemRequest", output = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItemResponse", fault = {
        @FaultAction(className = AutorizacaoException.class, value = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItem/Fault/AutorizacaoException")
    })
    public CadastrarItemResponse cadastrarItem(
        @WebParam(name = "cadastrarItem", targetNamespace = "http://ws.estoque.lheme.com.br/", partName = "parameters")
        CadastrarItem parameters,
        @WebParam(name = "tokenUsuario", targetNamespace = "http://ws.estoque.lheme.com.br/", header = true, partName = "tokenUsuario")
        TokenUsuario tokenUsuario)
        throws AutorizacaoException
    ;

}
